server:
  port: 6060
  servlet:
    context-path: /api

spring:
  application:
    name: guardianstack

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/guardian_stack
    username: guardian_app_user
    password: ${DB_PASSWORD:SecurePassword123} # Uses Env Var or default
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate Settings
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  # Email Configuration (Ready for Phase 4)
  mail:
    host: smtp.gmail.com
    port: 587
    username: rahmanrisan@gmail.com
    password: lxajxzbpfzrvlbes
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000

# Custom JWT Settings
app:
  security:
    jwt:
      secret: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      # Access Token: 15 Minutes (900,000 ms)
      expiration-ms: 900000 # 1 day in milliseconds
      refresh-token:
        # Refresh Token: 7 Days (604,800,000 ms)
        expiration: 604800000